#pragma once

#include "basic/black_kernel.hpp"
#include "basic/contrast_kernel.hpp"
#include "basic/exposure_kernel.hpp"
#include "basic/highlight_kernel.hpp"
#include "basic/shadow_kernel.hpp"
#include "basic/white_kernel.hpp"
#include "color/HLS_kernel.hpp"
#include "color/saturation_kernel.hpp"
#include "color/tint_kernel.hpp"
#include "color/vibrance_op.hpp"
#include "cst/cst_kernel.hpp"
#include "cst/lmt_kernel.hpp"
#include "curve/curve_kernel.hpp"
#include "detail/clarity_kernel.hpp"
#include "detail/sharpen_kernel.hpp"
#include "wheel/color_wheel_kernel.hpp"
