# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: semantic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'semantic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esemantic.proto\x12\x08semantic\"!\n\x0bPingRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"G\n\x0cPingResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nelapsed_ms\x18\x03 \x01(\x04\"H\n\x10\x45mbedTextRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\"k\n\x11\x45mbedImageRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0bimage_bytes\x18\x02 \x01(\x0c\x12\x19\n\x11image_format_hint\x18\x03 \x01(\t\x12\x12\n\nmodel_name\x18\x04 \x01(\t\"u\n\x11\x45mbeddingResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tembedding\x18\x02 \x03(\x02\x12\x11\n\tdimension\x18\x03 \x01(\r\x12\x12\n\nmodel_name\x18\x04 \x01(\t\x12\x12\n\nelapsed_ms\x18\x05 \x01(\x04\x32\xd6\x01\n\x0fSemanticService\x12\x35\n\x04Ping\x12\x15.semantic.PingRequest\x1a\x16.semantic.PingResponse\x12\x44\n\tEmbedText\x12\x1a.semantic.EmbedTextRequest\x1a\x1b.semantic.EmbeddingResponse\x12\x46\n\nEmbedImage\x12\x1b.semantic.EmbedImageRequest\x1a\x1b.semantic.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'semantic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=28
  _globals['_PINGREQUEST']._serialized_end=61
  _globals['_PINGRESPONSE']._serialized_start=63
  _globals['_PINGRESPONSE']._serialized_end=134
  _globals['_EMBEDTEXTREQUEST']._serialized_start=136
  _globals['_EMBEDTEXTREQUEST']._serialized_end=208
  _globals['_EMBEDIMAGEREQUEST']._serialized_start=210
  _globals['_EMBEDIMAGEREQUEST']._serialized_end=317
  _globals['_EMBEDDINGRESPONSE']._serialized_start=319
  _globals['_EMBEDDINGRESPONSE']._serialized_end=436
  _globals['_SEMANTICSERVICE']._serialized_start=439
  _globals['_SEMANTICSERVICE']._serialized_end=653
# @@protoc_insertion_point(module_scope)
